services:
  - type: web
    name: pa-jupyter-api
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: API_TOKEN
        sync: false
      - key: RUN_MODE
        value: "sync"
    healthCheckPath: "/"
    autoDeploy: true
